apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  name: titanic-pipeline-vpa-recom
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Workflow
    name:       titanic-pipeline-vpa-get-recom8xmpk
  updatePolicy:
    updateMode: "Off"