apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-titanic
  namespace: argo
spec:
  service:
    ports:
    - port: 8080
      targetPort: 8080
  webhook: 
    webhook-titanic:
      endpoint: /test
      method: POST
      port: "8080"
      url: ""