apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-first-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.11, pipelines.kubeflow.org/pipeline_compilation_time: '2022-01-31T13:49:38.674191',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "my first pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.11}
spec:
  entrypoint: my-first-pipeline
  templates:
  - name: for-loop-1
    inputs:
      parameters:
      - {name: number-generator-out-loop-item}
    dag:
      tasks:
      - name: item-printer
        template: item-printer
        arguments:
          parameters:
          - {name: number-generator-out-loop-item, value: '{{inputs.parameters.number-generator-out-loop-item}}'}
  - name: item-printer
    container:
      args: ['echo do output op1 item: {{inputs.parameters.number-generator-out-loop-item}}']
      command: [sh, -c]
      image: library/bash:4.4.23
    inputs:
      parameters:
      - {name: number-generator-out-loop-item}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: my-first-pipeline
    dag:
      tasks:
      - name: for-loop-1
        template: for-loop-1
        dependencies: [number-generator]
        arguments:
          parameters:
          - {name: number-generator-out-loop-item, value: '{{item}}'}
        withParam: '{{tasks.number-generator.outputs.parameters.number-generator-out}}'
      - {name: number-generator, template: number-generator}
      - name: total
        template: total
        dependencies: [number-generator]
        arguments:
          parameters:
          - {name: number-generator-out, value: '{{tasks.number-generator.outputs.parameters.number-generator-out}}'}
  - name: number-generator
    container:
      args: ['python -c "import random; import json; import sys; json.dump([i for
          i in range(20, 26)], open(''/tmp/out.json'', ''w''))"']
      command: [sh, -c]
      image: python:alpine3.6
    outputs:
      parameters:
      - name: number-generator-out
        valueFrom: {path: /tmp/out.json}
      artifacts:
      - {name: number-generator-out, path: /tmp/out.json}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: total
    container:
      args: ['echo output gen-numbers: {{inputs.parameters.number-generator-out}}
          && python -c "print(sum({{inputs.parameters.number-generator-out}}))"']
      command: [sh, -c]
      image: python:alpine3.6
    inputs:
      parameters:
      - {name: number-generator-out}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
