apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: titanic-survivor-prediction-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.11, pipelines.kubeflow.org/pipeline_compilation_time: '2022-02-09T20:47:17.775943',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "An example pipeline that
      trains and logs a ML model.", "inputs": [{"name": "traindata_url"}, {"name":
      "testdata_url"}, {"name": "param_url"}], "name": "TITANIC Survivor Prediction
      Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.11}
spec:
  entrypoint: titanic-survivor-prediction-pipeline
  templates:
  - name: preprocess-data
    container:
      args: [--traindata_url, '{{inputs.parameters.traindata_url}}', --testdata_url,
        '{{inputs.parameters.testdata_url}}']
      image: shamiulshifat/titanicprocess:v1
    inputs:
      parameters:
      - {name: testdata_url}
      - {name: traindata_url}
    outputs:
      artifacts:
      - {name: preprocess-data-X_test, path: /app/X_test.npy}
      - {name: preprocess-data-X_train, path: /app/X_train.npy}
      - {name: preprocess-data-X_valid, path: /app/X_valid.npy}
      - {name: preprocess-data-Y_train, path: /app/Y_train.npy}
      - {name: preprocess-data-Y_valid, path: /app/Y_valid.npy}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: test-model
    container:
      args: [--X_test, /tmp/inputs/input-0/data, --model, /tmp/inputs/input-1/data]
      image: shamiulshifat/titanicdeploy:v2
    inputs:
      artifacts:
      - {name: preprocess-data-X_test, path: /tmp/inputs/input-0/data}
      - {name: train-model-model, path: /tmp/inputs/input-1/data}
    outputs:
      artifacts:
      - {name: test-model-output, path: /app/titanic_predictions.csv}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: titanic-survivor-prediction-pipeline
    inputs:
      parameters:
      - {name: param_url}
      - {name: testdata_url}
      - {name: traindata_url}
    dag:
      tasks:
      - name: preprocess-data
        template: preprocess-data
        arguments:
          parameters:
          - {name: testdata_url, value: '{{inputs.parameters.testdata_url}}'}
          - {name: traindata_url, value: '{{inputs.parameters.traindata_url}}'}
      - name: test-model
        template: test-model
        dependencies: [preprocess-data, train-model]
        arguments:
          artifacts:
          - {name: preprocess-data-X_test, from: '{{tasks.preprocess-data.outputs.artifacts.preprocess-data-X_test}}'}
          - {name: train-model-model, from: '{{tasks.train-model.outputs.artifacts.train-model-model}}'}
      - name: train-model
        template: train-model
        dependencies: [preprocess-data]
        arguments:
          parameters:
          - {name: param_url, value: '{{inputs.parameters.param_url}}'}
          artifacts:
          - {name: preprocess-data-X_train, from: '{{tasks.preprocess-data.outputs.artifacts.preprocess-data-X_train}}'}
          - {name: preprocess-data-X_valid, from: '{{tasks.preprocess-data.outputs.artifacts.preprocess-data-X_valid}}'}
          - {name: preprocess-data-Y_train, from: '{{tasks.preprocess-data.outputs.artifacts.preprocess-data-Y_train}}'}
          - {name: preprocess-data-Y_valid, from: '{{tasks.preprocess-data.outputs.artifacts.preprocess-data-Y_valid}}'}
  - name: train-model
    container:
      args: [--param, '{{inputs.parameters.param_url}}', --X_train, /tmp/inputs/input-0/data,
        --Y_train, /tmp/inputs/input-1/data, --X_valid, /tmp/inputs/input-2/data,
        --Y_valid, /tmp/inputs/input-3/data]
      image: shamiulshifat/titanictrain:v3
    inputs:
      parameters:
      - {name: param_url}
      artifacts:
      - {name: preprocess-data-X_train, path: /tmp/inputs/input-0/data}
      - {name: preprocess-data-Y_train, path: /tmp/inputs/input-1/data}
      - {name: preprocess-data-X_valid, path: /tmp/inputs/input-2/data}
      - {name: preprocess-data-Y_valid, path: /tmp/inputs/input-3/data}
    outputs:
      artifacts:
      - {name: train-model-model, path: /app/model.pkl}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters:
    - {name: traindata_url}
    - {name: testdata_url}
    - {name: param_url}
  serviceAccountName: pipeline-runner
